### PR TITLE
Expand API command set coverage

### PR DESCRIPTION
**Pull request by renemarc**
Hey Bart,

Thanks for your Lightpack library! 😃

I've taken the liberty to add support for the few missing API commands, including those added by the now popular Lightpack Fork. I've tried to stay close to your coding style, but do feel free to comment or modify this PR if you see that something is off.

Main changes:
- Support API up to v2.2 (with compatibility checks)
- Add connection buffering
- Implement methods for all available API commands
- Add utility method for colour averaging

### CODE REVIEW

**Comment by tremby** [comment]
Cool! I didn't actually know there was a popular fork ([is this the one you mean?](https://github.com/psieg/Lightpack/)) -- when I switched from an x86 HTPC down to a Raspberry Pi I stopped using Prismatik and switched to [Hyperion](https://github.com/hyperion-project/hyperion). That was maybe two or three years ago.

I haven't even tried using py-lightpack on the same machine since then. I would like to get my audio visualizer script (which IIRC used py-lightpack) running again at some point, but finding time for projects like that is getting increasingly difficult.

If you want me to do a proper review and merge this, would you be able to split up the (large!) changeset into more manageable commits? If that's too daunting I'll still look it over, it just might take me longer.

Alternatively, should I add you as a maintainer?

Off topic, can I ask what you're using this for? Just curious. I didn't realize I actually had any users!

**Comment by renemarc** [comment]
Yup, that's the Prismatik Fork. :) I am still rocking an x86 HTPC with an 100-LEDs Adalight, and it works well with movies, video games, and general mood-lighting alike. I liked what @mihalski started with his [custom Lightpack component](https://github.com/mihalski/homeassistant/blob/master/custom_components/light/lightpack.py) for [Home Assistant](https://www.home-assistant.io/), and simply wanted to help in developing it into an official component. Your library should get a few more users then!

Regarding the PR ...true, it's a tad overkill indeed. I can split it up into a few chunks if you want, like socket buffering, command coverage, API upgrade, etc.. and open related issues. That should make things easier to review.

If you don't have a Lightpack setup to tests things and any incoming issues, I'd be honoured to help you in maintaining your library!

**Comment by tremby** [comment]
Pretty sure I could temporarily stop Hyperion and test on my Raspberry Pi,
though it's a single screen, single Lightpack setup.

Maybe this is the push I need to get my music visualizer working again, so
I do intend to do this, it just may take a while to find time.

Please do go ahead and split up the changeset if it's not too much bother.

I'll add you as a maintainer in due course.

If it looks likely this will be a little more widely used let's aim to
eventually add some tests too (though I'm not expecting you to add any
right away for this round of changes).

**Comment by renemarc** [comment]
Cool, I'll open a few issues and related PRs then!

**Comment by renemarc** [comment]
I've opened a few separate issues and submitted code chucks. Because they are all related to the same files, the PRs are cascaded instead of being based on the same branch. If any fixes are needed I can update and rebase accordingly.

Happy reviewing! 😄

**Comment by tremby** [comment]
I'll close this since your separate PRs supersede it.

**Pull request closed without merging**
